# Generated by Django 2.2.14 on 2020-07-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogoanime', '0002_auto_20200719_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mp4upload', 'mp4upload')], default='mp4upload', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gogoanime.Host'),
        ),
        migrations.AlterField(
            model_name='link',
            name='video_url',
            field=models.URLField(help_text='Enter video URL', max_length=300, verbose_name='Video URL'),
        ),
    ]
