# Generated by Django 2.2.14 on 2020-07-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogoanime', '0003_auto_20200719_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gogoanime.Host'),
        ),
        migrations.AlterField(
            model_name='link',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gogoanime.Site'),
        ),
    ]
